### ISSUE TITLE
Some questions about vision_tower.

### ISSUE THREAD

**Issue by 0x4e8** [Yaxin9Luo/Gamma-MOD#3]
Is the vision_tower you use in the code "clip-vit-large-patch14-336"? I can't load vision_tower when I use the "Gamma-MoD-llava-hr-7b-0.34" you provided. Even if I download "clip-vit-large-patch14-336" to a local folder and set the path correctly. Could you please provide me some specific implementation details to help me solve the problem? Thanks.

**Comment by 0x4e8** [comment]
Is it the reason of "convnext_large_mlp.clip_laion2b_ft_320"? Can you provide the download of "convnext_large_mlp.clip_laion2b_ft_320"?

**Comment by Yaxin9Luo** [comment]
hi, there are two vision encoders in original LLaVA-HR, you can download convnext_large_mlp.clip_laion2b_ft_320 from https://huggingface.co/timm/convnext_large_mlp.clip_laion2b_soup_ft_in12k_320 . Also plz notice that except MoD Related implementations, all the model configs are from the original MLLMs repo, so for LLaVA-HR you could refer to https://github.com/luogen1996/LLaVA-HR/tree/main for MGM you could refer to https://github.com/dvlab-research/MGM.

If you have further questions , I am glad to help, you could also provide the screenshot of the bugs for a better reference

**Comment by 0x4e8** [comment]
Thanks for your reply. It seems that I need to access huggingface even though I have downloaded the model locally.


Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/urllib3/connection.py", line 693, in connect
    self.sock = sock = self._new_conn()
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/urllib3/connection.py", line 208, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x146f59b0c610>, 'Connection to huggingface.co timed out. (connect timeout=10)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /timm/convnext_large_mlp.clip_laion2b_soup_ft_in12k_in1k_320/resolve/main/pytorch_model.bin (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x146f59b0c610>, 'Connection to huggingface.co timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1376, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1296, in get_hf_file_metadata
    r = _request_wrapper(
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 277, in _request_wrapper
    response = _request_wrapper(
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 300, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 93, in send
    return super().send(request, *args, **kwargs)
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/requests/adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /timm/convnext_large_mlp.clip_laion2b_soup_ft_in12k_in1k_320/resolve/main/pytorch_model.bin (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x146f59b0c610>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: bf1a8d70-2d28-49c4-928a-513d2a46ce1c)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/hy-tmp/Gamma-MOD/gamma_mod/eval/model_vqa_loader.py", line 165, in <module>
    eval_model(args)
  File "/hy-tmp/Gamma-MOD/gamma_mod/eval/model_vqa_loader.py", line 81, in eval_model
    tokenizer, model, image_processor, context_len = load_pretrained_model(model_path, args.model_base, model_name)
  File "/hy-tmp/Gamma-MOD/gamma_mod/model/builder.py", line 132, in load_pretrained_model
    model = EvalMoDLLaVALlamaForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, **kwargs)
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2700, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/hy-tmp/Gamma-MOD/gamma_mod/model/language_model/llava_llama_mod.py", line 577, in __init__
    super(EvalMoDLLaVALlamaForCausalLM, self).__init__(config)
  File "/hy-tmp/Gamma-MOD/gamma_mod/model/language_model/llava_llama_mod.py", line 424, in __init__
    self.model = MoDLLaVALlamaModel(config)
  File "/hy-tmp/Gamma-MOD/gamma_mod/model/language_model/llava_llama_mod.py", line 53, in __init__
    super(MoDLLaVALlamaModel, self).__init__(config)
  File "/hy-tmp/Gamma-MOD/gamma_mod/model/llava_arch.py", line 66, in __init__
    self.vision_tower = build_vision_tower(config, delay_load=delay_load)
  File "/hy-tmp/Gamma-MOD/gamma_mod/model/multimodal_encoder/builder.py", line 13, in build_vision_tower
    return MultiPathCLIPVisionTower(vision_tower, args=vision_tower_cfg, **kwargs)
  File "/hy-tmp/Gamma-MOD/gamma_mod/model/multimodal_encoder/multipath_encoder_wapper.py", line 116, in __init__
    self.slow_vision_tower = ConvNextVisionTower(args.vision_tower_slow, args,
  File "/hy-tmp/Gamma-MOD/gamma_mod/model/multimodal_encoder/convnext_encoder.py", line 42, in __init__
    self.load_model()
  File "/hy-tmp/Gamma-MOD/gamma_mod/model/multimodal_encoder/convnext_encoder.py", line 54, in load_model
    self.vision_tower = convnext_large_mlp(self.vision_tower_name)
  File "/hy-tmp/Gamma-MOD/gamma_mod/model/multimodal_encoder/convnext.py", line 1006, in convnext_large_mlp
    model = _create_convnext('convnext_large_mlp', pretrained=pretrained, **dict(model_args, **kwargs))
  File "/hy-tmp/Gamma-MOD/gamma_mod/model/multimodal_encoder/convnext.py", line 494, in _create_convnext
    model = build_model_with_cfg(
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/timm/models/_builder.py", line 397, in build_model_with_cfg
    load_pretrained(
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/timm/models/_builder.py", line 190, in load_pretrained
    state_dict = load_state_dict_from_hf(pretrained_loc)
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/timm/models/_hub.py", line 189, in load_state_dict_from_hf
    cached_file = hf_hub_download(hf_model_id, filename=filename, revision=hf_revision)
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 969, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/usr/local/miniconda3/envs/gamma-mod/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1487, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

**Comment by Yaxin9Luo** [comment]
It seems like you have some issues with the internet connection to Huggingface; maybe use a VPN?

**Comment by 0x4e8** [comment]
Thanks for your suggestion. Could you please take a look at the parameter "checkpoint_path" of the function "load_state_dict"?
The CKPT I used was Gamma-MoD-llava-hr-7b-0.34.
The function details are as follows:
```
def load_state_dict(
        checkpoint_path: str,
        use_ema: bool = True,
        device: Union[str, torch.device] = 'cpu',
) -> Dict[str, Any]:
```
The path of this function is:
![5ed048067dd8a11bbff7ff88be34ddd1](https://github.com/user-attachments/assets/466f0c9c-74f7-40f7-bc30-06da0b481e22)

**Comment by Yaxin9Luo** [comment]
Can I ask what is the problem with the checkpoint?

**Comment by 0x4e8** [comment]
Thanks for your response. Due to some restrictions, I can't access huggingface in this code, so I modified some codes to load my local file. But "convnext_large_mlp.clip_laion2b_soup_ft_in12k_in1k_320" has two weight models: model.safetensors and pytorch_model.bin, I want to know which one is loaded.

**Comment by Yaxin9Luo** [comment]
oh, I get it, usually, model.safetensors file is the huggingface format for a model's ckpt file, I am not sure whether you can still use it without access to huggingface, I suggest using pytorch_model.bin. But be aware that, if there are restrictions to hugging face, there will be more troubles like this, I guess. 
Here is an alternative website for huggingface, which is a mirror website of it, you can definitely access from China.
https://hf-mirror.com/timm/convnext_large_mlp.clip_laion2b_soup_ft_in12k_in1k_320

**Comment by 0x4e8** [comment]
Thank you very much for your suggestions.
